---
abstract: 'A featureful IRC bouncer based on POE::Component::IRC'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires:
  Test::Script: 1.07
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Bondage
no_index:
  directory:
    - t
    - utils
    - example
requires:
  POE::Component::Client::DNS: 0.99
  POE::Component::IRC: 6.06
  POE::Filter::IRCD: 2.34
  Proc::Daemon: 0
  YAML::XS: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-Bondage
  homepage: http://search.cpan.org/dist/App-Bondage/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hinrik/app-bondage.git
version: 0.4.8
x_authority: cpan:HINRIK
