--- #YAML:1.0
name:                App-Bondage
version:             0.3.1
abstract:            A featureful IRC bouncer based on POE::Component::IRC
license:             perl
author:              
    - Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Config:                        0
    Config::Any:                   0.11
    Digest::MD5:                   0
    File::Spec:                    0
    File::Temp:                    0
    POE::Component::Client::DNS:   0.99
    POE::Component::Daemon:        0
    POE::Component::IRC:           5.88
    POE::Filter::IRCD:             2.34
    Test::More:                    0
    Tie::File:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
