# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-Bondage
version:      0.2.5
version_from: lib/App/Bondage.pm
installdirs:  site
license:      perl
requires:
    Config::Any:                   0.11
    POE::Component::Client::DNS:   0.99
    POE::Component::Daemon:        0
    POE::Component::IRC:           5.62
    POE::Filter::IRCD:             2.34

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
